data_source:
    "pass"

current_db:
  data_dir: data/current_db
  data_source_dir: /opt/twc
  file_name: dnmp

retrieve_db:
  data_dir: data/retrieved_db
  output_file_name: retrieved_ips.csv
  iterations: 1

updated_db:
  data_dir: data/updated_db
  file_name: dnmp

final_db:
  data_dir: data/final_db
  file_name: dnmp
